apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 3  # Production: more replicas for high availability
  template:
    spec:
      containers:
        - name: lepa-portal
          image: nexlura/lepa-portal:latest
          envFrom:
            - configMapRef:
                name: nexlura-lepa-env-file