apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: lepa
spec:
  replicas: 2  # Staging: moderate replicas for testing
  template:
    spec:
      containers:
        - name: lepa-portal
          image: nexlura/lepa-portal-staging:latest
          envFrom:
            - configMapRef:
                name: nexlura-lepa-staging-env-file
