apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1  # dev: single replica for development
  template:
    spec:
      containers:
        - name: lepa-portal
          image: nexlura/lepa-portal-dev:latest
          envFrom:
            - configMapRef:
                name: nexlura-lepa-dev-env-file