apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lepa
spec:
  template:
    spec:
      containers:
        - name: lepa-ui
          image: nexlura/lepa-ui-dev:latest
          volumeMounts:
            - name: env-file
              mountPath: /.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: nexlura-lepa-dev-env-file