apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: lepa
spec:
  replicas: 1  # dev: single replica for development
  template:
    spec:
      containers:
        - name: lepa-portal
          image: nexlura/lepa-portal-dev:latest
          envFrom:
            - configMapRef:
                name: nexlura-lepa-dev-env-file
          volumeMounts:
            - name: env-file
              mountPath: /.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: nexlura-lepa-dev-env-file