apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lepa
resources:
  - ../../base
  - env-configmap.yaml
  - ingress.yaml

namePrefix: nexlura-lepa-production-
patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment