apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lepa-portal
  template:
    metadata:
      labels:
        app: lepa-portal
    spec:
      containers:
        - name: lepa-portal
          image: nexlura/lepa-portal:latest  # This will be overridden by overlays
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace