apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lepa
resources:
  - service.yaml
  - deployment.yaml

labels:
  - pairs:
      app: lepa-ui

commonAnnotations:
  app: lepa-ui

# Removed nameSuffix for cleaner naming